// SPDX-FileCopyrightText: 2025 models.dev contributors
// SPDX-FileCopyrightText: 2026 Kaushik Kumar
// SPDX-License-Identifier: MIT
// @generated by packages/ai/scripts/generate-catalog.ts; do not edit.

import type { ModelInfo } from "../model.ts";

export const MODELS: readonly ModelInfo[] = [
  {"providerId":"cerebras","modelId":"gemma-4-31b","displayName":"Gemma 4 31B IT","apiDialect":"openai-chat","capabilities":{"toolUse":true,"structuredOutput":true,"imageInput":true},"reasoning":true,"thinkingLevelMap":{"minimal":null,"low":"low","medium":"medium","high":"high","xhigh":null,"max":null,"off":"none"},"contextWindow":131072,"maxOutputTokens":40960,"cost":{"inputUsdPerMTok":0.99,"outputUsdPerMTok":1.49},"cache":{"supported":false,"defaultRetention":"none","supportedRetentions":["none"]},"endpoint":{"type":"fixed","baseUrl":"https://api.cerebras.ai/v1"},"availability":{"status":"preview","reason":"Source catalog status: beta"},"compatibility":{"dialect":"openai-chat","supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":false,"supportsUsageInStreaming":true,"maxTokensField":"max_tokens","supportsStrictTools":false,"supportsLongCacheRetention":false}},
  {"providerId":"cerebras","modelId":"gpt-oss-120b","displayName":"GPT OSS 120B","apiDialect":"openai-chat","capabilities":{"toolUse":true,"structuredOutput":true,"imageInput":false},"reasoning":true,"thinkingLevelMap":{"minimal":null,"low":"low","medium":"medium","high":"high","xhigh":null,"max":null},"contextWindow":131072,"maxOutputTokens":40960,"cost":{"inputUsdPerMTok":0.35,"outputUsdPerMTok":0.75},"cache":{"supported":false,"defaultRetention":"none","supportedRetentions":["none"]},"endpoint":{"type":"fixed","baseUrl":"https://api.cerebras.ai/v1"},"availability":{"status":"available"},"compatibility":{"dialect":"openai-chat","supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":false,"supportsUsageInStreaming":true,"maxTokensField":"max_tokens","supportsStrictTools":false,"supportsLongCacheRetention":false}},
];
