// SPDX-FileCopyrightText: 2026 Hari Srinivasan
// SPDX-License-Identifier: Apache-2.0

import type { ModelInfo } from "./model.ts";

const defaults = {
  providerId: "azure-openai",
  apiDialect: "openai-responses",
  capabilities: { toolUse: true, structuredOutput: true, imageInput: true },
} as const;

interface AzureModelDefinition {
  readonly modelId: string;
  readonly displayName: string;
  readonly reasoning: boolean;
  readonly contextWindow: number;
  readonly maxOutputTokens: number;
  readonly input: number;
  readonly output: number;
  readonly cacheRead?: number;
  readonly cacheWrite?: number;
  readonly imageInput?: boolean;
  readonly thinkingLevelMap?: ModelInfo["thinkingLevelMap"];
  readonly grammarTools?: boolean;
}

function azureModel(definition: AzureModelDefinition): ModelInfo {
  return {
    ...defaults,
    modelId: definition.modelId,
    displayName: definition.displayName,
    reasoning: definition.reasoning,
    capabilities: {
      ...defaults.capabilities,
      imageInput: definition.imageInput ?? true,
    },
    contextWindow: definition.contextWindow,
    maxOutputTokens: definition.maxOutputTokens,
    cost: {
      inputUsdPerMTok: definition.input,
      outputUsdPerMTok: definition.output,
      cacheReadUsdPerMTok: definition.cacheRead ?? 0,
      cacheWriteUsdPerMTok: definition.cacheWrite ?? 0,
    },
    ...(definition.thinkingLevelMap === undefined
      ? {}
      : { thinkingLevelMap: definition.thinkingLevelMap }),
    ...(definition.grammarTools
      ? {
          compatibility: {
            dialect: "openai-responses" as const,
            supportsGrammarTools: true,
          },
        }
      : {}),
  };
}

const GPT5_THINKING = { off: null } as const;
const GPT5_XHIGH_THINKING = { off: null, xhigh: "xhigh" } as const;
const GPT56_THINKING = { off: null, xhigh: "xhigh", max: "max" } as const;

/** Azure OpenAI model catalog used by the built-in provider. */
export const AZURE_OPENAI_MODELS: readonly ModelInfo[] = [
  azureModel({
    modelId: "gpt-4",
    displayName: "GPT-4",
    reasoning: false,
    imageInput: false,
    contextWindow: 8_192,
    maxOutputTokens: 8_192,
    input: 30,
    output: 60,
  }),
  azureModel({
    modelId: "gpt-4-turbo",
    displayName: "GPT-4 Turbo",
    reasoning: false,
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    input: 10,
    output: 30,
  }),
  azureModel({
    modelId: "gpt-4.1",
    displayName: "GPT-4.1",
    reasoning: false,
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    input: 2,
    output: 8,
    cacheRead: 0.5,
  }),
  azureModel({
    modelId: "gpt-4.1-mini",
    displayName: "GPT-4.1 mini",
    reasoning: false,
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    input: 0.4,
    output: 1.6,
    cacheRead: 0.1,
  }),
  azureModel({
    modelId: "gpt-4.1-nano",
    displayName: "GPT-4.1 nano",
    reasoning: false,
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    input: 0.1,
    output: 0.4,
    cacheRead: 0.025,
  }),
  azureModel({
    modelId: "gpt-4o",
    displayName: "GPT-4o",
    reasoning: false,
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: 2.5,
    output: 10,
    cacheRead: 1.25,
  }),
  azureModel({
    modelId: "gpt-4o-2024-05-13",
    displayName: "GPT-4o (2024-05-13)",
    reasoning: false,
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    input: 5,
    output: 15,
  }),
  azureModel({
    modelId: "gpt-4o-2024-08-06",
    displayName: "GPT-4o (2024-08-06)",
    reasoning: false,
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: 2.5,
    output: 10,
    cacheRead: 1.25,
  }),
  azureModel({
    modelId: "gpt-4o-2024-11-20",
    displayName: "GPT-4o (2024-11-20)",
    reasoning: false,
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: 2.5,
    output: 10,
    cacheRead: 1.25,
  }),
  azureModel({
    modelId: "gpt-4o-mini",
    displayName: "GPT-4o mini",
    reasoning: false,
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: 0.15,
    output: 0.6,
    cacheRead: 0.075,
  }),
  azureModel({
    modelId: "gpt-5",
    displayName: "GPT-5",
    reasoning: true,
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: 1.25,
    output: 10,
    cacheRead: 0.125,
    thinkingLevelMap: GPT5_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5-chat-latest",
    displayName: "GPT-5 Chat Latest",
    reasoning: false,
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: 1.25,
    output: 10,
    cacheRead: 0.125,
    thinkingLevelMap: GPT5_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5-mini",
    displayName: "GPT-5 Mini",
    reasoning: true,
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: 0.25,
    output: 2,
    cacheRead: 0.025,
    thinkingLevelMap: GPT5_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5-nano",
    displayName: "GPT-5 Nano",
    reasoning: true,
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: 0.05,
    output: 0.4,
    cacheRead: 0.005,
    thinkingLevelMap: GPT5_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5-pro",
    displayName: "GPT-5 Pro",
    reasoning: true,
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: 15,
    output: 120,
    thinkingLevelMap: GPT5_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.1",
    displayName: "GPT-5.1",
    reasoning: true,
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: 1.25,
    output: 10,
    cacheRead: 0.125,
    thinkingLevelMap: GPT5_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.2",
    displayName: "GPT-5.2",
    reasoning: true,
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: 1.75,
    output: 14,
    cacheRead: 0.175,
    thinkingLevelMap: GPT5_XHIGH_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.2-chat-latest",
    displayName: "GPT-5.2 Chat",
    reasoning: true,
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: 1.75,
    output: 14,
    cacheRead: 0.175,
    thinkingLevelMap: GPT5_XHIGH_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.2-pro",
    displayName: "GPT-5.2 Pro",
    reasoning: true,
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: 21,
    output: 168,
    thinkingLevelMap: GPT5_XHIGH_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.3-chat-latest",
    displayName: "GPT-5.3 Chat (latest)",
    reasoning: false,
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: 1.75,
    output: 14,
    cacheRead: 0.175,
    thinkingLevelMap: GPT5_XHIGH_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.3-codex",
    displayName: "GPT-5.3 Codex",
    reasoning: true,
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: 1.75,
    output: 14,
    cacheRead: 0.175,
    thinkingLevelMap: GPT5_XHIGH_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.3-codex-spark",
    displayName: "GPT-5.3 Codex Spark",
    reasoning: true,
    contextWindow: 128_000,
    maxOutputTokens: 32_000,
    input: 1.75,
    output: 14,
    cacheRead: 0.175,
    thinkingLevelMap: GPT5_XHIGH_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.4",
    displayName: "GPT-5.4",
    reasoning: true,
    contextWindow: 1_050_000,
    maxOutputTokens: 128_000,
    input: 2.5,
    output: 15,
    cacheRead: 0.25,
    thinkingLevelMap: GPT5_XHIGH_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.4-mini",
    displayName: "GPT-5.4 mini",
    reasoning: true,
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: 0.75,
    output: 4.5,
    cacheRead: 0.075,
    thinkingLevelMap: GPT5_XHIGH_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.4-nano",
    displayName: "GPT-5.4 nano",
    reasoning: true,
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: 0.2,
    output: 1.25,
    cacheRead: 0.02,
    thinkingLevelMap: GPT5_XHIGH_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.4-pro",
    displayName: "GPT-5.4 Pro",
    reasoning: true,
    contextWindow: 1_050_000,
    maxOutputTokens: 128_000,
    input: 30,
    output: 180,
    thinkingLevelMap: GPT5_XHIGH_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.5",
    displayName: "GPT-5.5",
    reasoning: true,
    contextWindow: 1_050_000,
    maxOutputTokens: 128_000,
    input: 5,
    output: 30,
    cacheRead: 0.5,
    thinkingLevelMap: GPT5_XHIGH_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.5-pro",
    displayName: "GPT-5.5 Pro",
    reasoning: true,
    contextWindow: 1_050_000,
    maxOutputTokens: 128_000,
    input: 30,
    output: 180,
    thinkingLevelMap: { ...GPT5_XHIGH_THINKING, minimal: null, low: null },
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    reasoning: true,
    contextWindow: 1_050_000,
    maxOutputTokens: 128_000,
    input: 0.2,
    output: 1.2,
    cacheRead: 0.02,
    cacheWrite: 0.25,
    thinkingLevelMap: GPT56_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    reasoning: true,
    contextWindow: 1_050_000,
    maxOutputTokens: 128_000,
    input: 5,
    output: 30,
    cacheRead: 0.5,
    cacheWrite: 6.25,
    thinkingLevelMap: GPT56_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    reasoning: true,
    contextWindow: 1_050_000,
    maxOutputTokens: 128_000,
    input: 2,
    output: 12,
    cacheRead: 0.2,
    cacheWrite: 2.5,
    thinkingLevelMap: GPT56_THINKING,
    grammarTools: true,
  }),
  azureModel({
    modelId: "gpt-realtime-2.1",
    displayName: "GPT-Realtime-2.1",
    reasoning: true,
    contextWindow: 128_000,
    maxOutputTokens: 32_000,
    input: 4,
    output: 24,
    cacheRead: 0.4,
  }),
  azureModel({
    modelId: "o1",
    displayName: "o1",
    reasoning: true,
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    input: 15,
    output: 60,
    cacheRead: 7.5,
  }),
  azureModel({
    modelId: "o1-pro",
    displayName: "o1-pro",
    reasoning: true,
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    input: 150,
    output: 600,
  }),
  azureModel({
    modelId: "o3",
    displayName: "o3",
    reasoning: true,
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    input: 2,
    output: 8,
    cacheRead: 0.5,
  }),
  azureModel({
    modelId: "o3-mini",
    displayName: "o3-mini",
    reasoning: true,
    imageInput: false,
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    input: 1.1,
    output: 4.4,
    cacheRead: 0.55,
  }),
  azureModel({
    modelId: "o3-pro",
    displayName: "o3-pro",
    reasoning: true,
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    input: 20,
    output: 80,
  }),
  azureModel({
    modelId: "o4-mini",
    displayName: "o4-mini",
    reasoning: true,
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    input: 1.1,
    output: 4.4,
    cacheRead: 0.275,
  }),
];
