// SPDX-FileCopyrightText: 2025 models.dev contributors
// SPDX-FileCopyrightText: 2026 Kaushik Kumar
// SPDX-License-Identifier: MIT
// @generated by packages/ai/scripts/generate-catalog.ts; do not edit.

import type { BuiltinCatalogProvider, CatalogProvenance } from "./catalog.ts";
import type { ModelInfo } from "./model.ts";
import { MODELS as AMAZON_BEDROCK_MODELS } from "./catalog.generated/amazon-bedrock.generated.ts";
import { MODELS as ANT_LING_MODELS } from "./catalog.generated/ant-ling.generated.ts";
import { MODELS as ANTHROPIC_MODELS } from "./catalog.generated/anthropic.generated.ts";
import { MODELS as AZURE_OPENAI_RESPONSES_MODELS } from "./catalog.generated/azure-openai-responses.generated.ts";
import { MODELS as BASETEN_MODELS } from "./catalog.generated/baseten.generated.ts";
import { MODELS as CEREBRAS_MODELS } from "./catalog.generated/cerebras.generated.ts";
import { MODELS as CLOUDFLARE_WORKERS_AI_MODELS } from "./catalog.generated/cloudflare-workers-ai.generated.ts";
import { MODELS as DEEPSEEK_MODELS } from "./catalog.generated/deepseek.generated.ts";
import { MODELS as FIREWORKS_MODELS } from "./catalog.generated/fireworks.generated.ts";
import { MODELS as GOOGLE_MODELS } from "./catalog.generated/google.generated.ts";
import { MODELS as GOOGLE_VERTEX_MODELS } from "./catalog.generated/google-vertex.generated.ts";
import { MODELS as GROQ_MODELS } from "./catalog.generated/groq.generated.ts";
import { MODELS as HUGGINGFACE_MODELS } from "./catalog.generated/huggingface.generated.ts";
import { MODELS as KIMI_CODING_MODELS } from "./catalog.generated/kimi-coding.generated.ts";
import { MODELS as MINIMAX_MODELS } from "./catalog.generated/minimax.generated.ts";
import { MODELS as MINIMAX_CN_MODELS } from "./catalog.generated/minimax-cn.generated.ts";
import { MODELS as MISTRAL_MODELS } from "./catalog.generated/mistral.generated.ts";
import { MODELS as MOONSHOTAI_MODELS } from "./catalog.generated/moonshotai.generated.ts";
import { MODELS as MOONSHOTAI_CN_MODELS } from "./catalog.generated/moonshotai-cn.generated.ts";
import { MODELS as NVIDIA_MODELS } from "./catalog.generated/nvidia.generated.ts";
import { MODELS as OPENAI_MODELS } from "./catalog.generated/openai.generated.ts";
import { MODELS as OPENAI_CODEX_MODELS } from "./catalog.generated/openai-codex.generated.ts";
import { MODELS as OPENCODE_MODELS } from "./catalog.generated/opencode.generated.ts";
import { MODELS as OPENCODE_GO_MODELS } from "./catalog.generated/opencode-go.generated.ts";
import { MODELS as QWEN_TOKEN_PLAN_MODELS } from "./catalog.generated/qwen-token-plan.generated.ts";
import { MODELS as QWEN_TOKEN_PLAN_CN_MODELS } from "./catalog.generated/qwen-token-plan-cn.generated.ts";
import { MODELS as QWEN_TOKEN_PLAN_INDIVIDUAL_MODELS } from "./catalog.generated/qwen-token-plan-individual.generated.ts";
import { MODELS as TOGETHER_MODELS } from "./catalog.generated/together.generated.ts";
import { MODELS as VERCEL_AI_GATEWAY_MODELS } from "./catalog.generated/vercel-ai-gateway.generated.ts";
import { MODELS as XAI_MODELS } from "./catalog.generated/xai.generated.ts";
import { MODELS as XIAOMI_MODELS } from "./catalog.generated/xiaomi.generated.ts";
import { MODELS as XIAOMI_TOKEN_PLAN_AMS_MODELS } from "./catalog.generated/xiaomi-token-plan-ams.generated.ts";
import { MODELS as XIAOMI_TOKEN_PLAN_CN_MODELS } from "./catalog.generated/xiaomi-token-plan-cn.generated.ts";
import { MODELS as XIAOMI_TOKEN_PLAN_SGP_MODELS } from "./catalog.generated/xiaomi-token-plan-sgp.generated.ts";
import { MODELS as ZAI_MODELS } from "./catalog.generated/zai.generated.ts";
import { MODELS as ZAI_CODING_CN_MODELS } from "./catalog.generated/zai-coding-cn.generated.ts";

export const GENERATED_CATALOG_PROVENANCE = {"generatedAt":"2026-09-05T13:49:08Z","sources":[{"name":"models.dev","location":"https://models.dev/api.json","retrievedAt":"2026-09-05T13:49:08Z","sha256":"0b09a4d8dedab6a804ca15046729bb2ec03c5f5b689b89a983ea488bb71eaeef","revision":"5c600a037417cf778ee6eb3ea2ce0f17abc12130","license":"MIT"},{"name":"Ant Ling official documentation","location":"https://developer.ant-ling.com/en/docs/api-reference/","retrievedAt":"2026-09-05T13:49:08Z","sha256":"3c715bab4b49c6b76d5f65ba7d3545ff20e9ed1fb793e9183cbf488ce47dd1ae","license":"factual metadata"}]} as const satisfies CatalogProvenance;

export const BUILTIN_CATALOG_PROVIDERS = [
  {"id":"amazon-bedrock","displayName":"Amazon Bedrock","catalogKind":"static"},
  {"id":"ant-ling","displayName":"Ant Ling","catalogKind":"static"},
  {"id":"anthropic","displayName":"Anthropic","catalogKind":"static"},
  {"id":"azure-openai-responses","displayName":"Azure OpenAI Responses","catalogKind":"static"},
  {"id":"baseten","displayName":"Baseten","catalogKind":"static"},
  {"id":"cerebras","displayName":"Cerebras","catalogKind":"static"},
  {"id":"cloudflare-ai-gateway","displayName":"Cloudflare AI Gateway","catalogKind":"dynamic"},
  {"id":"cloudflare-workers-ai","displayName":"Cloudflare Workers AI","catalogKind":"static"},
  {"id":"custom","displayName":"User configured endpoint","catalogKind":"configured"},
  {"id":"deepseek","displayName":"DeepSeek","catalogKind":"static"},
  {"id":"fireworks","displayName":"Fireworks AI","catalogKind":"static"},
  {"id":"github-copilot","displayName":"GitHub Copilot","catalogKind":"dynamic"},
  {"id":"google","displayName":"Google Generative AI","catalogKind":"static"},
  {"id":"google-vertex","displayName":"Google Vertex AI","catalogKind":"static"},
  {"id":"groq","displayName":"Groq","catalogKind":"static"},
  {"id":"huggingface","displayName":"Hugging Face","catalogKind":"static"},
  {"id":"kimi-coding","displayName":"Kimi For Coding","catalogKind":"static"},
  {"id":"minimax","displayName":"MiniMax","catalogKind":"static","regionFamily":"minimax","region":"global"},
  {"id":"minimax-cn","displayName":"MiniMax China","catalogKind":"static","regionFamily":"minimax","region":"cn"},
  {"id":"mistral","displayName":"Mistral","catalogKind":"static"},
  {"id":"moonshotai","displayName":"Moonshot AI","catalogKind":"static","regionFamily":"moonshotai","region":"global"},
  {"id":"moonshotai-cn","displayName":"Moonshot AI China","catalogKind":"static","regionFamily":"moonshotai","region":"cn"},
  {"id":"nvidia","displayName":"NVIDIA NIM","catalogKind":"static"},
  {"id":"openai","displayName":"OpenAI","catalogKind":"static"},
  {"id":"openai-codex","displayName":"OpenAI Codex","catalogKind":"static"},
  {"id":"opencode","displayName":"OpenCode Zen","catalogKind":"static"},
  {"id":"opencode-go","displayName":"OpenCode Go","catalogKind":"static"},
  {"id":"openrouter","displayName":"OpenRouter","catalogKind":"dynamic"},
  {"id":"qwen-token-plan","displayName":"Qwen Token Plan","catalogKind":"static","regionFamily":"qwen-token-plan","region":"sgp"},
  {"id":"qwen-token-plan-cn","displayName":"Qwen Token Plan China","catalogKind":"static","regionFamily":"qwen-token-plan","region":"cn"},
  {"id":"qwen-token-plan-individual","displayName":"Qwen Token Plan Individual","catalogKind":"static"},
  {"id":"radius","displayName":"Radius","catalogKind":"dynamic"},
  {"id":"together","displayName":"Together AI","catalogKind":"static"},
  {"id":"vercel-ai-gateway","displayName":"Vercel AI Gateway","catalogKind":"static"},
  {"id":"xai","displayName":"xAI","catalogKind":"static"},
  {"id":"xiaomi","displayName":"Xiaomi MiMo","catalogKind":"static","regionFamily":"xiaomi","region":"global"},
  {"id":"xiaomi-token-plan-ams","displayName":"Xiaomi Token Plan Amsterdam","catalogKind":"static","regionFamily":"xiaomi","region":"ams"},
  {"id":"xiaomi-token-plan-cn","displayName":"Xiaomi Token Plan China","catalogKind":"static","regionFamily":"xiaomi","region":"cn"},
  {"id":"xiaomi-token-plan-sgp","displayName":"Xiaomi Token Plan Singapore","catalogKind":"static","regionFamily":"xiaomi","region":"sgp"},
  {"id":"zai","displayName":"Z.AI","catalogKind":"static","regionFamily":"zai","region":"global"},
  {"id":"zai-coding-cn","displayName":"Z.AI Coding China","catalogKind":"static","regionFamily":"zai","region":"cn"},
] as const satisfies readonly BuiltinCatalogProvider[];

export const STATIC_MODEL_CATALOG: Readonly<Record<string, readonly ModelInfo[]>> = {
  "amazon-bedrock": AMAZON_BEDROCK_MODELS,
  "ant-ling": ANT_LING_MODELS,
  "anthropic": ANTHROPIC_MODELS,
  "azure-openai-responses": AZURE_OPENAI_RESPONSES_MODELS,
  "baseten": BASETEN_MODELS,
  "cerebras": CEREBRAS_MODELS,
  "cloudflare-workers-ai": CLOUDFLARE_WORKERS_AI_MODELS,
  "deepseek": DEEPSEEK_MODELS,
  "fireworks": FIREWORKS_MODELS,
  "google": GOOGLE_MODELS,
  "google-vertex": GOOGLE_VERTEX_MODELS,
  "groq": GROQ_MODELS,
  "huggingface": HUGGINGFACE_MODELS,
  "kimi-coding": KIMI_CODING_MODELS,
  "minimax": MINIMAX_MODELS,
  "minimax-cn": MINIMAX_CN_MODELS,
  "mistral": MISTRAL_MODELS,
  "moonshotai": MOONSHOTAI_MODELS,
  "moonshotai-cn": MOONSHOTAI_CN_MODELS,
  "nvidia": NVIDIA_MODELS,
  "openai": OPENAI_MODELS,
  "openai-codex": OPENAI_CODEX_MODELS,
  "opencode": OPENCODE_MODELS,
  "opencode-go": OPENCODE_GO_MODELS,
  "qwen-token-plan": QWEN_TOKEN_PLAN_MODELS,
  "qwen-token-plan-cn": QWEN_TOKEN_PLAN_CN_MODELS,
  "qwen-token-plan-individual": QWEN_TOKEN_PLAN_INDIVIDUAL_MODELS,
  "together": TOGETHER_MODELS,
  "vercel-ai-gateway": VERCEL_AI_GATEWAY_MODELS,
  "xai": XAI_MODELS,
  "xiaomi": XIAOMI_MODELS,
  "xiaomi-token-plan-ams": XIAOMI_TOKEN_PLAN_AMS_MODELS,
  "xiaomi-token-plan-cn": XIAOMI_TOKEN_PLAN_CN_MODELS,
  "xiaomi-token-plan-sgp": XIAOMI_TOKEN_PLAN_SGP_MODELS,
  "zai": ZAI_MODELS,
  "zai-coding-cn": ZAI_CODING_CN_MODELS,
};
