// SPDX-FileCopyrightText: 2026 Hari Srinivasan
// SPDX-License-Identifier: Apache-2.0

import type { ProviderAuthentication } from "./auth.ts";
import type { CatalogSnapshot, CatalogSourceMetadata } from "./catalog-store.ts";
import type {
  AuthMethod,
  ImageGenerationRequest,
  ImageGenerationResult,
  ImageModelInfo,
  ModelInfo,
  ModelRequest,
  ModelStreamEvent,
  SafeProviderDiagnostic,
} from "./model.ts";

export interface ModelCatalogRefreshContext {
  readonly providerId: string;
  /** Provider-instance-local generation. Results from older generations are never published. */
  readonly generation: number;
  /** Validated last-known-good snapshot restored before network work begins. */
  readonly previous?: Readonly<CatalogSnapshot>;
  readonly signal: AbortSignal;
}

interface ModelCatalogRefreshMetadata {
  readonly providerId: string;
  readonly generation: number;
  /** Safe public source metadata. URLs, headers, and credentials are intentionally absent. */
  readonly source: CatalogSourceMetadata;
  readonly diagnostics?: readonly SafeProviderDiagnostic[];
}

export type ModelCatalogRefreshResult =
  | (ModelCatalogRefreshMetadata & {
      readonly status: "updated";
      readonly models: readonly ModelInfo[];
      readonly imageModels?: readonly ImageModelInfo[];
      readonly sourceUpdatedAt?: number;
      readonly etag?: string;
    })
  | (ModelCatalogRefreshMetadata & {
      readonly status: "not_modified";
    });

/** Handle for a provider-side deferred response. Optional; no provider implements it yet. */
export interface DeferredResponse {
  readonly id: string;
  result(): Promise<AsyncIterable<ModelStreamEvent>>;
  cancel(): Promise<void>;
}

export interface ModelProvider {
  readonly id: string;
  readonly displayName: string;
  readonly authMethods: readonly AuthMethod[];
  /** Provider-owned, UI-neutral authentication lifecycle when authentication is configurable. */
  readonly authentication?: ProviderAuthentication;
  listModels(): Promise<readonly ModelInfo[]>;
  /** Legacy additive refresh shape retained for existing provider implementations. */
  refreshModels?(): Promise<readonly ModelInfo[]>;
  /** Context-aware explicit live catalog refresh with persistence metadata. */
  refreshModelCatalog?(context: ModelCatalogRefreshContext): Promise<ModelCatalogRefreshResult>;
  /**
   * Streams one model response. Failures before dispatch may throw; failures
   * after dispatch must terminate through a terminal stream event. Consumers
   * enforce this with `normalizeModelStream`.
   */
  stream(request: ModelRequest): AsyncIterable<ModelStreamEvent>;
  /** Dispatches a registry-resolved model, including a restored dynamic catalog model. */
  streamModel?(model: ModelInfo, request: ModelRequest): AsyncIterable<ModelStreamEvent>;
  /** Optional deferred-response seam. */
  defer?(request: ModelRequest): Promise<DeferredResponse>;
  /** Optional native image catalog owned by this same provider. */
  listImageModels?(): Promise<readonly ImageModelInfo[]>;
  /** Optional native image generation. Generated bytes must use the request blob writer. */
  generateImages?(request: ImageGenerationRequest): Promise<ImageGenerationResult>;
  dispose?(): void | Promise<void>;
}
