// SPDX-FileCopyrightText: 2026 Hari Srinivasan
// SPDX-License-Identifier: Apache-2.0

import type { ProviderAuthentication } from "./auth.ts";
import type {
  AuthMethod,
  ImageGenerationRequest,
  ImageGenerationResult,
  ImageModelInfo,
  ModelInfo,
  ModelRequest,
  ModelStreamEvent,
} from "./model.ts";

/** Handle for a provider-side deferred response. Optional; no provider implements it yet. */
export interface DeferredResponse {
  readonly id: string;
  result(): Promise<AsyncIterable<ModelStreamEvent>>;
  cancel(): Promise<void>;
}

export interface ModelProvider {
  readonly id: string;
  readonly displayName: string;
  readonly authMethods: readonly AuthMethod[];
  /** Provider-owned, UI-neutral authentication lifecycle when authentication is configurable. */
  readonly authentication?: ProviderAuthentication;
  listModels(): Promise<readonly ModelInfo[]>;
  /** Optional explicit live catalog refresh; providers without it have a static catalog. */
  refreshModels?(options: { readonly signal?: AbortSignal }): Promise<readonly ModelInfo[]>;
  /**
   * Streams one model response. Failures before dispatch may throw; failures
   * after dispatch must terminate through a terminal stream event. Consumers
   * enforce this with `normalizeModelStream`.
   */
  stream(request: ModelRequest): AsyncIterable<ModelStreamEvent>;
  /** Optional deferred-response seam. */
  defer?(request: ModelRequest): Promise<DeferredResponse>;
  /** Optional native image catalog owned by this same provider. */
  listImageModels?(): Promise<readonly ImageModelInfo[]>;
  /** Optional native image generation. Generated bytes must use the request blob writer. */
  generateImages?(request: ImageGenerationRequest): Promise<ImageGenerationResult>;
  dispose?(): void | Promise<void>;
}
